/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.shardingsphere.driver.jdbc.core.connection;

import lombok.Getter;
import org.apache.shardingsphere.driver.jdbc.adapter.AbstractConnectionAdapter;
import org.apache.shardingsphere.driver.jdbc.core.datasource.metadata.ShardingSphereDatabaseMetaData;
import org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSpherePreparedStatement;
import org.apache.shardingsphere.driver.jdbc.core.statement.ShardingSphereStatement;
import org.apache.shardingsphere.mode.manager.ContextManager;
import org.apache.shardingsphere.traffic.context.TrafficContextHolder;
import org.apache.shardingsphere.transaction.TransactionHolder;

import java.sql.Array;
import java.sql.DatabaseMetaData;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Savepoint;
import java.sql.Statement;

/**
 * ShardingSphere 的 JDBC 连接类。
 * 该类继承自 AbstractConnectionAdapter，是 JDBC Connection 的包装实现。
 * 提供了连接管理、事务控制、Statement/PreparedStatement 创建等能力。
 */
public final class ShardingSphereConnection extends AbstractConnectionAdapter {

    // 当前连接所属的逻辑 schema 名称（即数据库逻辑名）
    @Getter
    private final String schema;

    // 上下文管理器，用于获取元数据、事务、规则等 ShardingSphere 全局上下文信息
    @Getter
    private final ContextManager contextManager;

    // 封装的底层连接管理器，负责处理数据源连接、事务等
    @Getter
    private final ConnectionManager connectionManager;

    // 自动提交模式，默认 true（符合 JDBC 标准）
    private boolean autoCommit = true;

    // 当前事务隔离级别，默认 READ_UNCOMMITTED
    private int transactionIsolation = TRANSACTION_READ_UNCOMMITTED;

    // 只读模式，默认 false
    private boolean readOnly;

    // 连接关闭标志
    private volatile boolean closed;

    // 构造函数：初始化 schema 和上下文管理器
    public ShardingSphereConnection(final String schema, final ContextManager contextManager) {
        this.schema = schema;
        this.contextManager = contextManager;
        connectionManager = new ConnectionManager(schema, contextManager);
    }

    /**
     * Whether hold transaction or not.
     * 判断是否持有事务（即非自动提交状态）
     * @return true or false
     */
    public boolean isHoldTransaction() {
        return connectionManager.getConnectionTransaction().isHoldTransaction(autoCommit);
    }

    @Override
    public DatabaseMetaData getMetaData() {
        return new ShardingSphereDatabaseMetaData(this);
    }

    @Override
    public PreparedStatement prepareStatement(final String sql) throws SQLException {
        return new ShardingSpherePreparedStatement(this, sql);
    }

    @Override
    public PreparedStatement prepareStatement(final String sql, final int resultSetType, final int resultSetConcurrency) throws SQLException {
        return new ShardingSpherePreparedStatement(this, sql, resultSetType, resultSetConcurrency);
    }

    @Override
    public PreparedStatement prepareStatement(final String sql, final int resultSetType, final int resultSetConcurrency, final int resultSetHoldability) throws SQLException {
        return new ShardingSpherePreparedStatement(this, sql, resultSetType, resultSetConcurrency, resultSetHoldability);
    }

    @Override
    public PreparedStatement prepareStatement(final String sql, final int autoGeneratedKeys) throws SQLException {
        return new ShardingSpherePreparedStatement(this, sql, autoGeneratedKeys);
    }

    @Override
    public PreparedStatement prepareStatement(final String sql, final int[] columnIndexes) throws SQLException {
        return new ShardingSpherePreparedStatement(this, sql, Statement.RETURN_GENERATED_KEYS);
    }

    @Override
    public PreparedStatement prepareStatement(final String sql, final String[] columnNames) throws SQLException {
        return new ShardingSpherePreparedStatement(this, sql, Statement.RETURN_GENERATED_KEYS);
    }

    @Override
    public Statement createStatement() {
        return new ShardingSphereStatement(this);
    }

    @Override
    public Statement createStatement(final int resultSetType, final int resultSetConcurrency) {
        return new ShardingSphereStatement(this, resultSetType, resultSetConcurrency);
    }

    @Override
    public Statement createStatement(final int resultSetType, final int resultSetConcurrency, final int resultSetHoldability) {
        return new ShardingSphereStatement(this, resultSetType, resultSetConcurrency, resultSetHoldability);
    }

    @Override
    public boolean getAutoCommit() {
        return autoCommit;
    }

    @Override
    public void setAutoCommit(final boolean autoCommit) throws SQLException {
        this.autoCommit = autoCommit;
        if (connectionManager.getConnectionTransaction().isLocalTransaction()) {
            processLocalTransaction();
        } else {
            processDistributeTransaction();
        }
    }

    private void processLocalTransaction() throws SQLException {
        connectionManager.setAutoCommit(autoCommit);
        if (!autoCommit) {
            TransactionHolder.setInTransaction();
        }
    }

    private void processDistributeTransaction() throws SQLException {
        switch (connectionManager.getConnectionTransaction().getDistributedTransactionOperationType(autoCommit)) {
            case BEGIN:
                connectionManager.close();
                connectionManager.getConnectionTransaction().begin();
                TransactionHolder.setInTransaction();
                break;
            case COMMIT:
                connectionManager.getConnectionTransaction().commit();
                break;
            default:
                break;
        }
    }

    @Override
    public void commit() throws SQLException {
        try {
            connectionManager.commit();
        } finally {
            connectionManager.getConnectionTransaction().setRollbackOnly(false);
            TransactionHolder.clear();
            TrafficContextHolder.remove();
        }
    }

    @Override
    public void rollback() throws SQLException {
        try {
            connectionManager.rollback();
        } finally {
            connectionManager.getConnectionTransaction().setRollbackOnly(false);
            TransactionHolder.clear();
            TrafficContextHolder.remove();
        }
    }

    @Override
    public void rollback(final Savepoint savepoint) throws SQLException {
        checkClose();
        connectionManager.rollback(savepoint);
    }

    @Override
    public Savepoint setSavepoint(final String name) throws SQLException {
        checkClose();
        return connectionManager.setSavepoint(name);
    }

    @Override
    public Savepoint setSavepoint() throws SQLException {
        checkClose();
        return connectionManager.setSavepoint();
    }

    @Override
    public void releaseSavepoint(final Savepoint savepoint) throws SQLException {
        checkClose();
        connectionManager.releaseSavepoint(savepoint);
    }

    private void checkClose() throws SQLException {
        if (isClosed()) {
            throw new SQLException("This connection has been closed");
        }
    }

    @SuppressWarnings("MagicConstant")
    @Override
    public int getTransactionIsolation() throws SQLException {
        return connectionManager.getTransactionIsolation().orElseGet(() -> transactionIsolation);
    }

    @Override
    public void setTransactionIsolation(final int level) throws SQLException {
        transactionIsolation = level;
        connectionManager.setTransactionIsolation(level);
    }

    @Override
    public boolean isReadOnly() {
        return readOnly;
    }

    @Override
    public void setReadOnly(final boolean readOnly) throws SQLException {
        this.readOnly = readOnly;
        connectionManager.setReadOnly(readOnly);
    }

    @Override
    public boolean isValid(final int timeout) throws SQLException {
        return connectionManager.isValid(timeout);
    }

    @Override
    public Array createArrayOf(final String typeName, final Object[] elements) throws SQLException {
        return connectionManager.getRandomConnection().createArrayOf(typeName, elements);
    }

    @Override
    public boolean isClosed() {
        return closed;
    }

    @Override
    public void close() throws SQLException {
        closed = true;
        connectionManager.close();
    }
}
